Add some fields to systeminfo
iopsystems/rezolus pull request #100
Opened 2023-11-09 02:02 UTC by yangxi

2023-11-09 17:46 UTC, brayniac requested changes

2023-11-09 19:49 UTC, yangxi commented on crates/systeminfo/src/hwinfo/cpu.rs
> +pub fn get_cpu_boosting() -> Option<bool> {
Using enum is much better, thanks.

2023-11-09 19:50 UTC, yangxi commented on crates/systeminfo/src/hwinfo/cpu.rs
> +pub fn get_cpu_smt() -> Option<bool> {
Updated, please have a look when you have time

2024-03-15 21:07 UTC, yangxi commented on crates/systeminfo/src/hwinfo/util.rs
> +        hex_string.chars().rfold(0, |acc, c: char| {
Because this is a CPU bitmap so the number of bits can be larger than primitive types, so I switch to use char::to_digit(16).

2024-03-15 21:22 UTC, brayniac approved these changes

2024-03-15 21:23 UTC, merged